# Generated by Django 5.0.6 on 2026-09-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('order_status', 'Buyurtma holati'), ('new_order', 'Yangi buyurtma'), ('feedback', 'Fikr-mulohaza'), ('system', 'Tizim')], default='system', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
