# Generated by Django 5.0.6 on 2026-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('order_status', 'Статус заказа'), ('new_order', 'Новый заказ'), ('feedback', 'Обратная связь'), ('system', 'Система')], default='system', max_length=20),
        ),
    ]
