# Generated by Django 5.0.6 on 2026-09-05 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparing', 'Готовится'), ('in_progress', 'В процессе'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.table', verbose_name='Стол'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('preparing', 'Готовится'), ('in_progress', 'В процессе'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], max_length=20),
        ),
    ]
