# Generated by Django 5.0.6 on 2026-09-03 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Stol raqami')),
                ('name', models.CharField(blank=True, help_text='Masalan: "Zal 1", "Terasa"', max_length=50, verbose_name='Nom (zall/zona)')),
                ('seats', models.PositiveSmallIntegerField(default=4, verbose_name='O‘rindiqlar soni')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR token')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'db_table': 'tables',
                'ordering': ['number'],
            },
        ),
    ]
